### ISSUE TITLE
Action __construct

### ISSUE THREAD

**Issue by nenads** [dillingham/nova-assertions#17]
Hi,

any suggestion

```
class Delete extends DestructiveAction
{

    protected $modelId;

    public function __construct($modelId)
    {
        $this->modelId = $modelId;       
    }
```

How to use it with

```
$response->assertActionsInclude(Delete::class)
```
It will create error: **Unresolvable dependency resolving [Parameter #0 [ <required> $modelId ]] in class App\Nova\Actions\Delete**

while

```
$response->assertActionsInclude(new Delete(1))
```
Creates:  **Illegal offset type in isset or empty**

any suggestion how to assert Nova Actions that have constructor

**Comment by dillingham** [comment]
```

$response->assertActions(function($actions) {
    return $actions[0]->modelId == 1;
});

```

Maybe use the callback approach for that 

Although the assertions are really to show the action exists on the page. Not that it was selected. Good luck
