### ISSUE TITLE
assertCanView Question

### ISSUE THREAD

**Issue by francoisauclair911** [dillingham/nova-assertions#3]
Hi, thank you for your package!

Quick question, what does the "assertCanView" tests exactly ?

When my user visits the "users" ressources he can view (little eye icon) some users he manages, but some he can't, how would I test for this using AssertCanView ?

I end up testing like the following but I wonder if there is a better way
```

public function it_cannot_view_users_he_doesnt_manage()

    {

        $response = $this->novaDetail('users', $this->notManagedUser->id);

        $response->assertForbidden();

    }

```
Thanks

**Comment by dillingham** [comment]
@francoisauclair911

->authorizedToView() is a policy boolean Nova adds in the response

It dictates showing rows and stuff.. the way you're doing it is correct though.
