### ISSUE TITLE
Is this replacement of Laravel Dusk tests

### ISSUE THREAD

**Issue by BobbyBorisov** [dillingham/nova-assertions#7]
Hey guys, I just found this package and it looks awesome! I wonder if this is a alternative for the Dusk test and how everybody is using it?

**Comment by dillingham** [comment]
Most cases you just want to know if things are or are not present in the json response.
Personally it felt like dusk tests to verify that things are present felt like overkill.

**Comment by BobbyBorisov** [comment]
@dillingham Fair enough. Thank you for the awesome package! Clicking on buttons and stuff is not my favorite part as well. Cheers!
